version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/host-data:/host-data
    ports:
      - 5432:5432
    expose:
      - 5432
